name = "ModFest 'Dragon'"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aa103cc7727fe07711f679873fe76a1a6dbd204a49bb2a222cbb5586a3187cc"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
