name = "ModFest 'Dragon'"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab6a3ca2517e74dfd7684ba60df0b7b657cb7799ef0c8cd6ada3c52398e0a770"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
