name = "ModFest 'Dragon'"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32bf9bdf8e6e67679682e4bc7428d23274a3b8fde12f321248507f58104b035e"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
