name = "Modfest - Carnival"
author = "ModFest"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d696e07a7bda13ab458b57589a2d69ef6e826c7c62e18f841112a48a3e7fed3a"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
