name = "Modfest - Carnival"
author = "ModFest"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c86bee23cf0428ea927858220622c96d163aecd7b78f546853013a085a9cb13c"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
