name = "Modfest - Carnival"
author = "ModFest"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8858e92eac1c820f9a737b2a8d074c5011917cb1f4642f9d3859620e5cb31e88"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
